// This file is auto-generated by scripts/generate-blurhash.js
// Run: bun run scripts/generate-blurhash.js

export const blurhashes = {
	"traversable_wormholes": "|78NYmoh56WCbwS5xBt5RjxA9wWCxaoeNKWBocfR00NK^%t6xHn~NbWCs,R%?G$y57Rj%1t6NGazxvxaEAIpk7j@s:axs:WYNER:~B%1E2WBkCocjKW9I-%1IqIqs:bHR-jd$*NGIpIp-n%1oLjbNcxaxWbHkC%0E3M|t6",
	"feathered_peacoq": "|A7-sfNG?KWB-=sX%et8kQx^M|RiRlR~RlbWRkRPt8RjRiaxNFj=f9obM|xvt7axxtozt7tRoyoft8RjW-WBkWV@bHV@WEo#k9WUoeWUk9ozbFayoga}WBbGWVaykDj[WBfhf6j]j[j]j@fia{kCfifkoffjj?a#j[fikC"
} as const;
