// This file is auto-generated by scripts/generate-blurhash.js
// Run: bun run scripts/generate-blurhash.js

export const blurhashes = {
	"invariant": "|LGRSORj0fWBV@WqNHayWB~qRkM{WVWBj[f6j[WC0Nf7%0oebHoLoej[WVICkBbboLj?kCkBjuoL$~s:RkWDayoej[a#oftRWCV@j[a#j[ayjufkR-R+j@s:j[fkj[f7a}w]s.WXa}ofj[a#a}oLSgayaebHofoLjZoej@",
	"tpwhb": "|EA9~Fa0D%?FRQRl%2V@oL~AMxIp?aM{RjxuV@ae?aE2Ip-:M{NGxuf5js%ME2EMx]M|R+t7adjY%MM|NGtRRjR*S4ayof%2adjFt7WBWDNbbbj]xajFn%ofjZoMR+bHbHofjZj?WCoet6V[oeofbIj@j[WCs.s.V@s.oe",
	"scienceviz": "|A7-seNG?KWB%gsX%et8kQx^M|RiRlR~RlbWRkRPt8RjRiaxNFj=f9obM|xvt7axxtozt7tRoyoft8RjW-WBkVV@bHV@WEozk9WUoeWUk9ozbFayoga}WBbGWVaykCj[WBfif6j]j[j]j[fia{kCj?fkoffjj?azj[fikC",
	"wormhole": "|67UD#V-0Lob?HW7ImbKxbNOx6tB9aab-toHNFaxD~R=-qj_9hWa%AoiV{s$oiWExUt79tad?HWXt5jWn+R*bas*alRpxnjca#WVR;j;s:acNLs%n#awk9k9e,RoWYobaxWCWAobobWUR+oLofofbIjujXWWj]flWCaeoc",
	"gwp": "|24eQYTeDzv0ELpf^,EJH;MvaIp0pKogVXRNo#tnInent8kqs:V?NFt7xupJogVrRNofp0o~i]RNI-s8t8OZsAnMNFxbo$g4ogjEV?ayo#g4fPi^n$WBbIs;WqWAnhWUkDwcS2W=xGS2WUw{ShW=s;W;WBniW;bcs:WBWA"
} as const;
